<a href="https://colab.research.google.com/github/BhargavAniketh2626/MachineLearning/blob/main/Machine_learning_skilling_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Data - Preprocessing**

**1.Importing Libraries**

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

**2.Importing Dataset**

In [3]:
df = pd.read_csv('housing.csv')
df

longitude  latitude  ...  median_house_value  ocean_proximity
0        -122.23     37.88  ...            452600.0         NEAR BAY
1        -122.22     37.86  ...            358500.0         NEAR BAY
2        -122.24     37.85  ...            352100.0         NEAR BAY
3        -122.25     37.85  ...            341300.0         NEAR BAY
4        -122.25     37.85  ...            342200.0         NEAR BAY
...          ...       ...  ...                 ...              ...
20635    -121.09     39.48  ...             78100.0           INLAND
20636    -121.21     39.49  ...             77100.0           INLAND
20637    -121.22     39.43  ...             92300.0           INLAND
20638    -121.32     39.43  ...             84700.0           INLAND
20639    -121.24     39.37  ...             89400.0           INLAND

[20640 rows x 10 columns]

**3.Finding out the null values and Update it**

In [13]:
df.isnull().values.any()

True

In [14]:
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [19]:
x = df.iloc[:, 4:5].values
y = df.iloc[:, -1].values

In [20]:
print(x)

[[ 129.]
 [1106.]
 [ 190.]
 ...
 [ 485.]
 [ 409.]
 [ 616.]]


In [21]:
print(y)

['NEAR BAY' 'NEAR BAY' 'NEAR BAY' ... 'INLAND' 'INLAND' 'INLAND']


In [23]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, :])
x[:, :] = imputer.transform(x[:, :])

In [24]:
print(x)

[[ 129.]
 [1106.]
 [ 190.]
 ...
 [ 485.]
 [ 409.]
 [ 616.]]


In [27]:
df['total_bedrooms'].isnull().values.any()

True

In [28]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [29]:
print(x)

  (0, 128)	1.0
  (1, 1104)	1.0
  (2, 189)	1.0
  (3, 234)	1.0
  (4, 279)	1.0
  (5, 212)	1.0
  (6, 488)	1.0
  (7, 687)	1.0
  (8, 665)	1.0
  (9, 707)	1.0
  (10, 433)	1.0
  (11, 752)	1.0
  (12, 473)	1.0
  (13, 190)	1.0
  (14, 626)	1.0
  (15, 282)	1.0
  (16, 346)	1.0
  (17, 292)	1.0
  (18, 454)	1.0
  (19, 297)	1.0
  (20, 183)	1.0
  (21, 366)	1.0
  (22, 541)	1.0
  (23, 336)	1.0
  (24, 436)	1.0
  :	:
  (20615, 215)	1.0
  (20616, 440)	1.0
  (20617, 108)	1.0
  (20618, 246)	1.0
  (20619, 339)	1.0
  (20620, 40)	1.0
  (20621, 246)	1.0
  (20622, 146)	1.0
  (20623, 243)	1.0
  (20624, 299)	1.0
  (20625, 16)	1.0
  (20626, 183)	1.0
  (20627, 64)	1.0
  (20628, 420)	1.0
  (20629, 1623)	1.0
  (20630, 504)	1.0
  (20631, 492)	1.0
  (20632, 415)	1.0
  (20633, 411)	1.0
  (20634, 394)	1.0
  (20635, 373)	1.0
  (20636, 149)	1.0
  (20637, 484)	1.0
  (20638, 408)	1.0
  (20639, 616)	1.0


In [30]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [34]:
print(y)

[3 3 3 ... 1 1 1]


In [39]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size = 4/5, random_state = 1)

TypeError: ignored